### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by phenix3443**

### CODE REVIEW

**Comment by hsyodyssey** [comment]
I think some not all English words should be separated with spaces.

**Comment by phenix3443** [comment]
"我们讲通过" should be "我们将通过"

**Comment by hsyodyssey** [comment]
Thanks for your help, as I just said, I'm revise this part, which has been modified in the not-yet-committed version.

**Comment by hsyodyssey** [comment]
Thanks.

**Comment by phenix3443** [comment]
You're welcome  ^_^

**Comment by hsyodyssey** [comment]
You have inspired me to checkout a "stable branch". I didn't care too much about this since I was maintaining this repo myself. Please forgive me for using English, I plan to write an English version afterwards. So it would be better to use English for all the records in the PR discussion.

**Pull request closed without merging**
